	<script type="text/javascript" src="PERCH_LOGINPATH/plugins/editors/tiny_mce/jquery.tinymce.js"></script>
	<script type="text/javascript" src="PERCH_LOGINPATH/plugins/editors/tiny_mce/tiny_mce.js"></script>
	<script type="text/javascript" src="PERCH_LOGINPATH/plugins/editors/tiny_mce/config.js"></script>
	<!-- <link rel="stylesheet" href="PERCH_LOGINPATH/plugins/editors/tiny_mce/themes/simple/skins/default/content.css" type="text/css" media="screen" charset="utf-8"/> -->
        